[package]
name = "mrload/knitt"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2.0.0"
BufferUtil = "sleitnick/buffer-util@0.3.1"
Component = "sleitnick/component@2.4.8"
EnumList = "sleitnick/enum-list@2.1.0"
Signal = "sleitnick/signal@2.0.1"
Concur = "sleitnick/concur@0.1.2"
Trove = "sleitnick/trove@1.3.0"
Knit = "sleitnick/knit@^1.7.0"
Input = "sleitnick/input@2.3.0"
Log = "sleitnick/log@0.1.1"
Option = "sleitnick/option@1.0.5"
Quaternion = "sleitnick/quaternion@0.2.3"
Sequent = "sleitnick/sequent@0.1.0"
Ser = "sleitnick/ser@1.0.5"
Silo = "sleitnick/silo@0.2.0"
Streamable = "sleitnick/streamable@1.2.4"
Symbol = "sleitnick/symbol@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
TaskQueue = "sleitnick/task-queue@1.0.0"
Timer = "sleitnick/timer@1.1.2"
Tree = "sleitnick/tree@1.1.0"
Trove = "sleitnick/trove@1.3.0"
TypedRemote = "sleitnick/typed-remote@0.1.0"
WaitFor = "sleitnick/wait-for@1.0.0"

Fusion = "acecateer/fusion@0.3.1"

ZonePlus = "mattschrubb/zoneplus@3.2.0"
Janitor = "howmanysmall/janitor@1.17.0"